---
  - name: "Playing with Ansible"
    hosts: k3s-nodes
    tasks:

    - name: "just execute a ls -lrt command"
      shell: "ls -lrt"
      register: "output"

    - debug: var=output.stdout_lines
